// AUTO-GENERATED by sources/scripts/genVoices.ts — do not edit by hand.
// Source: Volcano voice catalog, filtered to ResourceID === 'seed-tts-2.0' (50 voices).

export interface Voice {
    /** Volcano VoiceType, e.g. zh_female_vv_uranus_bigtts */
    voiceType: string;
    /** Volcano ResourceID; always 'seed-tts-2.0'. Sent to the gateway alongside voiceType. */
    resourceId: string;
    /** Display name (Chinese, from the catalog) */
    name: string;
    /** Display name (English) */
    nameEn: string;
    /** Description (Chinese, from the catalog) */
    description: string;
    /** Description (English) */
    descriptionEn: string;
    /** Avatar image URL */
    avatar: string;
    /** Preview/trial audio URL (wav) */
    trialUrl: string;
    /** '女' | '男' */
    gender: '女' | '男';
    /** Concatenated supported-language flag emojis (multilingual hint), may be empty. */
    flags: string;
}

/** Default voice used when the user hasn't picked one (matches the gateway env default). */
export const DEFAULT_VOICE_TYPE = 'zh_female_vv_uranus_bigtts';

export const VOICES: Voice[] = [
    {
        "voiceType": "zh_female_vv_uranus_bigtts",
        "resourceId": "seed-tts-2.0",
        "name": "Vivi 2.0",
        "nameEn": "Vivi 2.0",
        "description": "语调平稳、咬字柔和、自带治愈安抚力的女声音色",
        "descriptionEn": "A soothing female voice — steady tone, soft articulation, naturally calming.",
        "avatar": "https://lf3-static.bytednsdoc.com/obj/eden-cn/lm_hz_ihsph/ljhwZthlaukjlkulzlp/portal/bigtts/avatar/vivi_v2.png",
        "trialUrl": "https://lf3-static.bytednsdoc.com/obj/eden-cn/lm_hz_ihsph/ljhwZthlaukjlkulzlp/portal/bigtts/zh_female_vv_uranus_bigtts.wav",
        "gender": "女",
        "flags": "🇨🇳🇺🇸🇯🇵🇮🇩🇲🇽"
    },
    {
        "voiceType": "zh_female_xiaohe_uranus_bigtts",
        "resourceId": "seed-tts-2.0",
        "name": "小何 2.0",
        "nameEn": "Xiaohe 2.0",
        "description": "声线甜美有活力的妹妹，活泼开朗，笑容明媚。",
        "descriptionEn": "A sweet, energetic younger sister — lively, cheerful and bright.",
        "avatar": "https://lf3-static.bytednsdoc.com/obj/eden-cn/lm_hz_ihsph/ljhwZthlaukjlkulzlp/portal/bigtts/avatar/小何.png",
        "trialUrl": "https://lf3-static.bytednsdoc.com/obj/eden-cn/lm_hz_ihsph/ljhwZthlaukjlkulzlp/portal/bigtts/zh_female_xiaohe_uranus_bigtts.mp3",
        "gender": "女",
        "flags": "🇨🇳🇺🇸"
    },
    {
        "voiceType": "zh_male_wennuanahu_uranus_bigtts",
        "resourceId": "seed-tts-2.0",
        "name": "温暖阿虎/Alvin 2.0",
        "nameEn": "Alvin 2.0",
        "description": "声线阳光温暖、语气亲切，活力满满的少年音",
        "descriptionEn": "A warm, sunny youth voice — friendly and full of energy.",
        "avatar": "https://lf3-static.bytednsdoc.com/obj/eden-cn/lm_hz_ihsph/ljhwZthlaukjlkulzlp/portal/bigtts/avatar/温暖阿虎.png",
        "trialUrl": "https://lf3-static.bytednsdoc.com/obj/eden-cn/lm_hz_ihsph/ljhwZthlaukjlkulzlp/portal/bigtts/zh_male_wennuanahu_uranus_bigtts.mp3",
        "gender": "男",
        "flags": "🇨🇳🇺🇸"
    },
    {
        "voiceType": "zh_female_wenroumama_uranus_bigtts",
        "resourceId": "seed-tts-2.0",
        "name": "温柔妈妈 2.0",
        "nameEn": "Gentle Mom 2.0",
        "description": "语调舒缓、咬字温润，自带母性柔光的治愈女声",
        "descriptionEn": "A soothing motherly voice — slow, mellow and tender.",
        "avatar": "https://lf3-static.bytednsdoc.com/obj/eden-cn/lm_hz_ihsph/ljhwZthlaukjlkulzlp/portal/bigtts/avatar/温柔妈妈_副本.png",
        "trialUrl": "https://lf3-static.bytednsdoc.com/obj/eden-cn/lm_hz_ihsph/ljhwZthlaukjlkulzlp/portal/bigtts/zh_female_wenroumama_uranus_bigtts.mp3",
        "gender": "女",
        "flags": "🇨🇳🇺🇸"
    },
    {
        "voiceType": "zh_female_qiaopinv_uranus_bigtts",
        "resourceId": "seed-tts-2.0",
        "name": "俏皮女声 2.0",
        "nameEn": "Playful Girl 2.0",
        "description": "语调灵动跳脱、元气满满，古灵精怪的少女音",
        "descriptionEn": "A lively, spirited girl voice — quirky and full of energy.",
        "avatar": "https://lf3-static.bytednsdoc.com/obj/eden-cn/lm_hz_ihsph/ljhwZthlaukjlkulzlp/portal/bigtts/avatar/俏皮女声.png",
        "trialUrl": "https://lf3-static.bytednsdoc.com/obj/eden-cn/lm_hz_ihsph/ljhwZthlaukjlkulzlp/portal/bigtts/zh_female_qiaopinv_uranus_bigtts.mp3",
        "gender": "女",
        "flags": "🇨🇳🇺🇸"
    },
    {
        "voiceType": "zh_male_guanggaojieshuo_uranus_bigtts",
        "resourceId": "seed-tts-2.0",
        "name": "广告解说 2.0",
        "nameEn": "Ad Narrator 2.0",
        "description": "语调明快、感染力拉满，专业感十足的解说音",
        "descriptionEn": "A bright, highly engaging professional narration voice.",
        "avatar": "https://lf3-static.bytednsdoc.com/obj/eden-cn/lm_hz_ihsph/ljhwZthlaukjlkulzlp/portal/bigtts/avatar/广告解说.png",
        "trialUrl": "https://lf3-static.bytednsdoc.com/obj/eden-cn/lm_hz_ihsph/ljhwZthlaukjlkulzlp/portal/bigtts/zh_male_guanggaojieshuo_uranus_bigtts.mp3",
        "gender": "男",
        "flags": "🇨🇳🇺🇸"
    },
    {
        "voiceType": "zh_male_tiancaitongsheng_uranus_bigtts",
        "resourceId": "seed-tts-2.0",
        "name": "天才童声 2.0",
        "nameEn": "Prodigy Kid 2.0",
        "description": "声线清亮稚嫩、天赋感拉满，灵动清澈的童声",
        "descriptionEn": "A clear, youthful child voice — bright and gifted.",
        "avatar": "https://lf3-static.bytednsdoc.com/obj/eden-cn/lm_hz_ihsph/ljhwZthlaukjlkulzlp/portal/bigtts/avatar/天才童声.png",
        "trialUrl": "https://lf3-static.bytednsdoc.com/obj/eden-cn/lm_hz_ihsph/ljhwZthlaukjlkulzlp/portal/bigtts/zh_male_tiancaitongsheng_uranus_bigtts.mp3",
        "gender": "男",
        "flags": "🇨🇳🇺🇸"
    },
    {
        "voiceType": "zh_female_wenrouxiaoya_uranus_bigtts",
        "resourceId": "seed-tts-2.0",
        "name": "温柔小雅 2.0",
        "nameEn": "Gentle Yaya 2.0",
        "description": "语调轻柔、咬字温婉，气质娴静的淑女音",
        "descriptionEn": "A soft, graceful lady voice — gentle and serene.",
        "avatar": "https://lf3-static.bytednsdoc.com/obj/eden-cn/lm_hz_ihsph/ljhwZthlaukjlkulzlp/portal/bigtts/avatar/温柔小雅.png",
        "trialUrl": "https://lf3-static.bytednsdoc.com/obj/eden-cn/lm_hz_ihsph/ljhwZthlaukjlkulzlp/portal/bigtts/zh_female_wenrouxiaoya_uranus_bigtts.mp3",
        "gender": "女",
        "flags": "🇨🇳🇺🇸"
    },
    {
        "voiceType": "zh_female_roumeinvyou_uranus_bigtts",
        "resourceId": "seed-tts-2.0",
        "name": "柔美女友 2.0",
        "nameEn": "Sweet Girlfriend 2.0",
        "description": "语调软糯、语气娇柔，像女友般贴心的治愈女声",
        "descriptionEn": "A soft, tender voice — caring and soothing like a girlfriend.",
        "avatar": "https://lf3-static.bytednsdoc.com/obj/eden-cn/lm_hz_ihsph/ljhwZthlaukjlkulzlp/portal/bigtts/avatar/柔美女友.png",
        "trialUrl": "https://lf3-static.bytednsdoc.com/obj/eden-cn/lm_hz_ihsph/ljhwZthlaukjlkulzlp/portal/bigtts/zh_female_roumeinvyou_uranus_bigtts.mp3",
        "gender": "女",
        "flags": "🇨🇳🇺🇸"
    },
    {
        "voiceType": "zh_male_wenrouxiaoge_uranus_bigtts",
        "resourceId": "seed-tts-2.0",
        "name": "温柔小哥 2.0",
        "nameEn": "Gentle Guy 2.0",
        "description": "语调温柔、声线干净，气质谦和的青年男声",
        "descriptionEn": "A gentle young man voice — clean and modest.",
        "avatar": "https://lf3-static.bytednsdoc.com/obj/eden-cn/lm_hz_ihsph/ljhwZthlaukjlkulzlp/portal/bigtts/avatar/温柔小哥.png",
        "trialUrl": "https://lf3-static.bytednsdoc.com/obj/eden-cn/lm_hz_ihsph/ljhwZthlaukjlkulzlp/portal/bigtts/zh_male_wenrouxiaoge_uranus_bigtts.mp3",
        "gender": "男",
        "flags": "🇨🇳🇺🇸"
    },
    {
        "voiceType": "zh_female_tianmeiyueyue_uranus_bigtts",
        "resourceId": "seed-tts-2.0",
        "name": "甜美悦悦 2.0",
        "nameEn": "Sweet Yueyue 2.0",
        "description": "声线甜美软糯、语气娇俏，元气满满的甜妹音",
        "descriptionEn": "A sweet, soft and playful voice full of energy.",
        "avatar": "https://lf3-static.bytednsdoc.com/obj/eden-cn/lm_hz_ihsph/ljhwZthlaukjlkulzlp/portal/bigtts/avatar/甜美悦悦.png",
        "trialUrl": "https://lf3-static.bytednsdoc.com/obj/eden-cn/lm_hz_ihsph/ljhwZthlaukjlkulzlp/portal/bigtts/zh_female_tianmeiyueyue_uranus_bigtts.mp3",
        "gender": "女",
        "flags": "🇨🇳🇺🇸"
    },
    {
        "voiceType": "zh_female_qingchezizi_uranus_bigtts",
        "resourceId": "seed-tts-2.0",
        "name": "清澈梓梓  2.0",
        "nameEn": "Clear Zizi 2.0",
        "description": "声线清澈干净、语调温柔，气质纯净的少年音",
        "descriptionEn": "A clear, clean and gentle youthful voice — pure in tone.",
        "avatar": "https://lf3-static.bytednsdoc.com/obj/eden-cn/lm_hz_ihsph/ljhwZthlaukjlkulzlp/portal/bigtts/avatar/清澈梓梓.png",
        "trialUrl": "https://lf3-static.bytednsdoc.com/obj/eden-cn/lm_hz_ihsph/ljhwZthlaukjlkulzlp/portal/bigtts/zh_female_qingchezizi_uranus_bigtts.mp3",
        "gender": "女",
        "flags": "🇨🇳🇺🇸"
    },
    {
        "voiceType": "zh_male_yangguangqingnian_uranus_bigtts",
        "resourceId": "seed-tts-2.0",
        "name": "阳光青年 2.0",
        "nameEn": "Sunny Youth 2.0",
        "description": "声线阳光、语气开朗，充满活力的青年男声",
        "descriptionEn": "A sunny, cheerful young man voice full of energy.",
        "avatar": "https://lf3-static.bytednsdoc.com/obj/eden-cn/lm_hz_ihsph/ljhwZthlaukjlkulzlp/portal/bigtts/avatar/阳光青年.png",
        "trialUrl": "https://lf3-static.bytednsdoc.com/obj/eden-cn/lm_hz_ihsph/ljhwZthlaukjlkulzlp/portal/bigtts/zh_male_yangguangqingnian_uranus_bigtts.mp3",
        "gender": "男",
        "flags": "🇨🇳🇺🇸"
    },
    {
        "voiceType": "zh_male_yuanboxiaoshu_uranus_bigtts",
        "resourceId": "seed-tts-2.0",
        "name": "渊博小叔 2.0",
        "nameEn": "Worldly Uncle 2.0",
        "description": "声线沉稳、语调平缓，阅历感十足的叔音",
        "descriptionEn": "A steady, even-toned mature voice with a sense of experience.",
        "avatar": "https://lf3-static.bytednsdoc.com/obj/eden-cn/lm_hz_ihsph/ljhwZthlaukjlkulzlp/portal/bigtts/avatar/渊博小叔.png",
        "trialUrl": "https://lf3-static.bytednsdoc.com/obj/eden-cn/lm_hz_ihsph/ljhwZthlaukjlkulzlp/portal/bigtts/zh_male_yuanboxiaoshu_uranus_bigtts.mp3",
        "gender": "男",
        "flags": "🇨🇳🇺🇸"
    },
    {
        "voiceType": "zh_male_qingshuangnanda_uranus_bigtts",
        "resourceId": "seed-tts-2.0",
        "name": "清爽男大 2.0",
        "nameEn": "Fresh Campus Guy 2.0",
        "description": "声线干净清爽、语气阳光，元气满满的大学生音",
        "descriptionEn": "A clean, refreshing and sunny college-student voice.",
        "avatar": "https://lf3-static.bytednsdoc.com/obj/eden-cn/lm_hz_ihsph/ljhwZthlaukjlkulzlp/portal/bigtts/avatar/清爽男大.png",
        "trialUrl": "https://lf3-static.bytednsdoc.com/obj/eden-cn/lm_hz_ihsph/ljhwZthlaukjlkulzlp/portal/bigtts/zh_male_qingshuangnanda_uranus_bigtts.mp3",
        "gender": "男",
        "flags": "🇨🇳🇺🇸"
    },
    {
        "voiceType": "zh_female_zhixingnv_uranus_bigtts",
        "resourceId": "seed-tts-2.0",
        "name": "知性女声 2.0",
        "nameEn": "Intellectual Woman 2.0",
        "description": "语调沉稳、咬字清晰，气质知性的成熟女声",
        "descriptionEn": "A composed, clear mature female voice with an intellectual air.",
        "avatar": "https://lf3-static.bytednsdoc.com/obj/eden-cn/lm_hz_ihsph/ljhwZthlaukjlkulzlp/portal/bigtts/avatar/知性女声.png",
        "trialUrl": "https://lf3-static.bytednsdoc.com/obj/eden-cn/lm_hz_ihsph/ljhwZthlaukjlkulzlp/portal/bigtts/zh_female_zhixingnv_uranus_bigtts.mp3",
        "gender": "女",
        "flags": "🇨🇳🇺🇸"
    },
    {
        "voiceType": "zh_female_wenjingmaomao_uranus_bigtts",
        "resourceId": "seed-tts-2.0",
        "name": "文静毛毛 2.0",
        "nameEn": "Quiet Maomao 2.0",
        "description": "语调轻柔、声线软萌，安静乖巧的萝莉音",
        "descriptionEn": "A soft, sweet and quiet little-girl voice.",
        "avatar": "https://lf3-static.bytednsdoc.com/obj/eden-cn/lm_hz_ihsph/ljhwZthlaukjlkulzlp/portal/bigtts/avatar/文静毛毛.png",
        "trialUrl": "https://lf3-static.bytednsdoc.com/obj/eden-cn/lm_hz_ihsph/ljhwZthlaukjlkulzlp/portal/bigtts/zh_female_wenjingmaomao_uranus_bigtts.mp3",
        "gender": "女",
        "flags": "🇨🇳🇺🇸"
    },
    {
        "voiceType": "zh_male_kailangxuezhang_uranus_bigtts",
        "resourceId": "seed-tts-2.0",
        "name": "开朗学长 2.0",
        "nameEn": "Cheerful Senior 2.0",
        "description": "声线阳光、语气爽朗，阳光开朗的学长音",
        "descriptionEn": "A sunny, hearty senior-schoolmate voice.",
        "avatar": "https://lf3-static.bytednsdoc.com/obj/eden-cn/lm_hz_ihsph/ljhwZthlaukjlkulzlp/portal/bigtts/avatar/开朗学长.png",
        "trialUrl": "https://lf3-static.bytednsdoc.com/obj/eden-cn/lm_hz_ihsph/ljhwZthlaukjlkulzlp/portal/bigtts/zh_male_kailangxuezhang_uranus_bigtts.mp3",
        "gender": "男",
        "flags": "🇨🇳🇺🇸"
    },
    {
        "voiceType": "zh_male_kuailexiaodong_uranus_bigtts",
        "resourceId": "seed-tts-2.0",
        "name": "快乐小东 2.0",
        "nameEn": "Happy Xiaodong 2.0",
        "description": "语调明快、声线阳光，元气满满的青年男声",
        "descriptionEn": "A bright, sunny young man voice full of energy.",
        "avatar": "https://lf3-static.bytednsdoc.com/obj/eden-cn/lm_hz_ihsph/ljhwZthlaukjlkulzlp/portal/bigtts/avatar/快乐小东.png",
        "trialUrl": "https://lf3-static.bytednsdoc.com/obj/eden-cn/lm_hz_ihsph/ljhwZthlaukjlkulzlp/portal/bigtts/zh_male_kuailexiaodong_uranus_bigtts.mp3",
        "gender": "男",
        "flags": "🇨🇳🇺🇸"
    },
    {
        "voiceType": "zh_female_qinqienv_uranus_bigtts",
        "resourceId": "seed-tts-2.0",
        "name": "亲切女声 2.0",
        "nameEn": "Friendly Woman 2.0",
        "description": "语调温柔、语气亲切，像家人般暖心的治愈女声",
        "descriptionEn": "A gentle, warm voice — soothing like family.",
        "avatar": "https://lf3-static.bytednsdoc.com/obj/eden-cn/lm_hz_ihsph/ljhwZthlaukjlkulzlp/portal/bigtts/avatar/亲切女声.png",
        "trialUrl": "https://lf3-static.bytednsdoc.com/obj/eden-cn/lm_hz_ihsph/ljhwZthlaukjlkulzlp/portal/bigtts/zh_female_qinqienv_uranus_bigtts.mp3",
        "gender": "女",
        "flags": "🇨🇳🇺🇸"
    },
    {
        "voiceType": "zh_female_sophie_uranus_bigtts",
        "resourceId": "seed-tts-2.0",
        "name": "魅力苏菲 2.0",
        "nameEn": "Charming Sophie 2.0",
        "description": "高冷御姐，外表疏离难亲近，内心却细腻柔软",
        "descriptionEn": "An aloof, elegant lady — distant on the surface, tender within.",
        "avatar": "https://lf3-static.bytednsdoc.com/obj/eden-cn/lm_hz_ihsph/ljhwZthlaukjlkulzlp/portal/bigtts/avatar/Sophie.png",
        "trialUrl": "https://lf3-static.bytednsdoc.com/obj/eden-cn/lm_hz_ihsph/ljhwZthlaukjlkulzlp/portal/bigtts/zh_male_sophie_uranus_bigtts.mp3",
        "gender": "女",
        "flags": "🇨🇳🇺🇸"
    },
    {
        "voiceType": "zh_female_chanmeinv_uranus_bigtts",
        "resourceId": "seed-tts-2.0",
        "name": "谄媚女声 2.0",
        "nameEn": "Flattering Woman 2.0",
        "description": "语调软糯、语气讨好，自带逢迎感的女声",
        "descriptionEn": "A soft, ingratiating female voice.",
        "avatar": "https://lf3-static.bytednsdoc.com/obj/eden-cn/lm_hz_ihsph/ljhwZthlaukjlkulzlp/portal/bigtts/avatar/谄媚女声.png",
        "trialUrl": "https://lf3-static.bytednsdoc.com/obj/eden-cn/lm_hz_ihsph/ljhwZthlaukjlkulzlp/portal/bigtts/zh_female_chanmeinv_uranus_bigtts.mp3",
        "gender": "女",
        "flags": "🇨🇳🇺🇸"
    },
    {
        "voiceType": "zh_male_kailangdidi_uranus_bigtts",
        "resourceId": "seed-tts-2.0",
        "name": "开朗弟弟 2.0",
        "nameEn": "Cheerful Little Brother 2.0",
        "description": "声线阳光、语气活泼，元气满满的少年音，像邻家弟弟般亲切治愈",
        "descriptionEn": "A sunny, lively boy voice — warm and friendly like the kid next door.",
        "avatar": "https://lf3-static.bytednsdoc.com/obj/eden-cn/lm_hz_ihsph/ljhwZthlaukjlkulzlp/portal/bigtts/avatar/开朗弟弟.png",
        "trialUrl": "https://lf3-static.bytednsdoc.com/obj/eden-cn/lm_hz_ihsph/ljhwZthlaukjlkulzlp/portal/bigtts/zh_male_kailangdidi_uranus_bigtts.mp3",
        "gender": "男",
        "flags": "🇨🇳🇺🇸"
    },
    {
        "voiceType": "zh_female_jiaochuannv_uranus_bigtts",
        "resourceId": "seed-tts-2.0",
        "name": "娇喘女声 2.0",
        "nameEn": "Breathy Woman 2.0",
        "description": "语调软糯、语气娇柔，自带氛围感的甜妹音",
        "descriptionEn": "A soft, tender voice with an intimate, atmospheric tone.",
        "avatar": "https://lf3-static.bytednsdoc.com/obj/eden-cn/lm_hz_ihsph/ljhwZthlaukjlkulzlp/portal/bigtts/avatar/娇喘女声.png",
        "trialUrl": "https://lf3-static.bytednsdoc.com/obj/eden-cn/lm_hz_ihsph/ljhwZthlaukjlkulzlp/portal/bigtts/zh_female_jiaochuannv_uranus_bigtts.mp3",
        "gender": "女",
        "flags": "🇨🇳🇺🇸"
    },
    {
        "voiceType": "zh_female_mengyatou_uranus_bigtts",
        "resourceId": "seed-tts-2.0",
        "name": "萌丫头/Cutey 2.0",
        "nameEn": "Cutey 2.0",
        "description": "声线软萌稚嫩、语气娇俏，元气满满的萝莉音",
        "descriptionEn": "A soft, sweet and playful little-girl voice full of energy.",
        "avatar": "https://lf3-static.bytednsdoc.com/obj/eden-cn/lm_hz_ihsph/ljhwZthlaukjlkulzlp/portal/bigtts/avatar/萌丫头.png",
        "trialUrl": "https://lf3-static.bytednsdoc.com/obj/eden-cn/lm_hz_ihsph/ljhwZthlaukjlkulzlp/portal/bigtts/zh_female_mengyatou_uranus_bigtts.mp3",
        "gender": "女",
        "flags": "🇨🇳🇺🇸"
    },
    {
        "voiceType": "zh_female_gaolengyujie_uranus_bigtts",
        "resourceId": "seed-tts-2.0",
        "name": "高冷御姐 2.0",
        "nameEn": "Cool Lady 2.0",
        "description": "声线清冷疏离、气场强大，冷静干练的御姐音",
        "descriptionEn": "A cool, aloof and commanding mature-woman voice — calm and capable.",
        "avatar": "https://lf3-static.bytednsdoc.com/obj/eden-cn/lm_hz_ihsph/ljhwZthlaukjlkulzlp/portal/bigtts/avatar/高冷御姐.png",
        "trialUrl": "https://lf3-static.bytednsdoc.com/obj/eden-cn/lm_hz_ihsph/ljhwZthlaukjlkulzlp/portal/bigtts/zh_female_gaolengyujie_uranus_bigtts.mp3",
        "gender": "女",
        "flags": "🇨🇳🇺🇸"
    },
    {
        "voiceType": "zh_female_kailangjiejie_uranus_bigtts",
        "resourceId": "seed-tts-2.0",
        "name": "开朗姐姐  2.0",
        "nameEn": "Cheerful Big Sister 2.0",
        "description": "语调明快、声线爽朗，阳光开朗的大姐姐音",
        "descriptionEn": "A bright, hearty and sunny big-sister voice.",
        "avatar": "https://lf3-static.bytednsdoc.com/obj/eden-cn/lm_hz_ihsph/ljhwZthlaukjlkulzlp/portal/bigtts/avatar/开朗姐姐.png",
        "trialUrl": "https://lf3-static.bytednsdoc.com/obj/eden-cn/lm_hz_ihsph/ljhwZthlaukjlkulzlp/portal/bigtts/zh_female_kailangjiejie_uranus_bigtts.mp3",
        "gender": "女",
        "flags": "🇨🇳🇺🇸"
    },
    {
        "voiceType": "zh_male_liangsangmengzai_uranus_bigtts",
        "resourceId": "seed-tts-2.0",
        "name": "亮嗓萌仔 2.0",
        "nameEn": "Bright Kiddo 2.0",
        "description": "声线清亮稚嫩、元气满满，活泼开朗的童声",
        "descriptionEn": "A clear, youthful child voice — lively and cheerful.",
        "avatar": "https://lf3-static.bytednsdoc.com/obj/eden-cn/lm_hz_ihsph/ljhwZthlaukjlkulzlp/portal/bigtts/avatar/亮嗓萌仔.png",
        "trialUrl": "https://lf3-static.bytednsdoc.com/obj/eden-cn/lm_hz_ihsph/ljhwZthlaukjlkulzlp/portal/bigtts/zh_male_liangsangmengzai_uranus_bigtts.mp3",
        "gender": "男",
        "flags": "🇨🇳🇺🇸"
    },
    {
        "voiceType": "zh_male_cixingjieshuonan_uranus_bigtts",
        "resourceId": "seed-tts-2.0",
        "name": "磁性解说男声/Morgan 2.0",
        "nameEn": "Morgan 2.0",
        "description": "声线磁性浑厚、语调沉稳，专业感拉满的解说男声",
        "descriptionEn": "A magnetic, deep and steady professional male narration voice.",
        "avatar": "https://lf3-static.bytednsdoc.com/obj/eden-cn/lm_hz_ihsph/ljhwZthlaukjlkulzlp/portal/bigtts/avatar/磁性解说男声.png",
        "trialUrl": "https://lf3-static.bytednsdoc.com/obj/eden-cn/lm_hz_ihsph/ljhwZthlaukjlkulzlp/portal/bigtts/zh_male_cixingjieshuonan_uranus_bigtts.mp3",
        "gender": "男",
        "flags": "🇨🇳🇺🇸"
    },
    {
        "voiceType": "zh_female_jitangmei_uranus_bigtts",
        "resourceId": "seed-tts-2.0",
        "name": "鸡汤妹妹/Hope 2.0",
        "nameEn": "Hope 2.0",
        "description": "语调温暖、语气治愈，充满正能量的甜妹音",
        "descriptionEn": "A warm, healing voice full of positive energy.",
        "avatar": "https://lf3-static.bytednsdoc.com/obj/eden-cn/lm_hz_ihsph/ljhwZthlaukjlkulzlp/portal/bigtts/avatar/鸡汤妹妹.png",
        "trialUrl": "https://lf3-static.bytednsdoc.com/obj/eden-cn/lm_hz_ihsph/ljhwZthlaukjlkulzlp/portal/bigtts/zh_female_jitangmei_uranus_bigtts.mp3",
        "gender": "女",
        "flags": "🇨🇳🇺🇸"
    },
    {
        "voiceType": "zh_female_tiexinnvsheng_uranus_bigtts",
        "resourceId": "seed-tts-2.0",
        "name": "贴心女声/Candy 2.0",
        "nameEn": "Candy 2.0",
        "description": "语调温柔、语气亲切，像闺蜜般贴心的治愈女声",
        "descriptionEn": "A gentle, friendly voice — caring like a close friend.",
        "avatar": "https://lf3-static.bytednsdoc.com/obj/eden-cn/lm_hz_ihsph/ljhwZthlaukjlkulzlp/portal/bigtts/avatar/贴心女声.png",
        "trialUrl": "https://lf3-static.bytednsdoc.com/obj/eden-cn/lm_hz_ihsph/ljhwZthlaukjlkulzlp/portal/bigtts/zh_female_tiexinnvsheng_uranus_bigtts.mp3",
        "gender": "女",
        "flags": "🇨🇳🇺🇸"
    },
    {
        "voiceType": "zh_male_huolixiaoge_uranus_bigtts",
        "resourceId": "seed-tts-2.0",
        "name": "活力小哥 2.0",
        "nameEn": "Lively Guy 2.0",
        "description": "语速明快、声线阳光，元气满满的青年男声",
        "descriptionEn": "A brisk, sunny young man voice full of energy.",
        "avatar": "https://lf3-static.bytednsdoc.com/obj/eden-cn/lm_hz_ihsph/ljhwZthlaukjlkulzlp/portal/bigtts/avatar/活力小哥.png",
        "trialUrl": "https://lf3-static.bytednsdoc.com/obj/eden-cn/lm_hz_ihsph/ljhwZthlaukjlkulzlp/portal/bigtts/zh_male_huolixiaoge_uranus_bigtts.mp3",
        "gender": "男",
        "flags": "🇨🇳🇺🇸"
    },
    {
        "voiceType": "zh_female_wenroushunv_uranus_bigtts",
        "resourceId": "seed-tts-2.0",
        "name": "温柔淑女 2.0",
        "nameEn": "Gentle Lady 2.0",
        "description": "语调轻柔、咬字温婉，气质娴静的淑女音，自带大家闺秀的温婉感",
        "descriptionEn": "A soft, graceful lady voice with a refined, well-bred warmth.",
        "avatar": "https://lf3-static.bytednsdoc.com/obj/eden-cn/lm_hz_ihsph/ljhwZthlaukjlkulzlp/portal/bigtts/avatar/温柔淑女.png",
        "trialUrl": "https://lf3-static.bytednsdoc.com/obj/eden-cn/lm_hz_ihsph/ljhwZthlaukjlkulzlp/portal/bigtts/zh_female_wenroushunv_uranus_bigtts.mp3",
        "gender": "女",
        "flags": "🇨🇳🇺🇸"
    },
    {
        "voiceType": "zh_male_fanjuanqingnian_uranus_bigtts",
        "resourceId": "seed-tts-2.0",
        "name": "反卷青年 2.0",
        "nameEn": "Easygoing Youth 2.0",
        "description": "语气松弛随性、语调慵懒，佛系通透的青年音",
        "descriptionEn": "A relaxed, laid-back youth voice — chill and carefree.",
        "avatar": "https://lf3-static.bytednsdoc.com/obj/eden-cn/lm_hz_ihsph/ljhwZthlaukjlkulzlp/portal/bigtts/avatar/反卷青年.png",
        "trialUrl": "https://lf3-static.bytednsdoc.com/obj/eden-cn/lm_hz_ihsph/ljhwZthlaukjlkulzlp/portal/bigtts/zh_male_fanjuanqingnian_uranus_bigtts.mp3",
        "gender": "男",
        "flags": "🇨🇳🇺🇸"
    },
    {
        "voiceType": "zh_male_lanyinmianbao_uranus_bigtts",
        "resourceId": "seed-tts-2.0",
        "name": "懒音绵宝 2.0",
        "nameEn": "Lazy Mianbao 2.0",
        "description": "语调慵懒软糯、声线软绵，自带慵懒感的儿童音",
        "descriptionEn": "A lazy, soft and cottony child voice.",
        "avatar": "https://lf3-static.bytednsdoc.com/obj/eden-cn/lm_hz_ihsph/ljhwZthlaukjlkulzlp/portal/bigtts/avatar/懒音绵宝.png",
        "trialUrl": "https://lf3-static.bytednsdoc.com/obj/eden-cn/lm_hz_ihsph/ljhwZthlaukjlkulzlp/portal/bigtts/zh_male_lanyinmianbao_uranus_bigtts.mp3",
        "gender": "男",
        "flags": "🇨🇳🇺🇸"
    },
    {
        "voiceType": "zh_female_popo_uranus_bigtts",
        "resourceId": "seed-tts-2.0",
        "name": "婆婆 2.0",
        "nameEn": "Granny 2.0",
        "description": "语调舒缓、声线慈祥，自带岁月感的长辈女声",
        "descriptionEn": "A mellow, kindly elder-woman voice with a sense of years.",
        "avatar": "https://lf3-static.bytednsdoc.com/obj/eden-cn/lm_hz_ihsph/ljhwZthlaukjlkulzlp/portal/bigtts/avatar/婆婆.png",
        "trialUrl": "https://lf3-static.bytednsdoc.com/obj/eden-cn/lm_hz_ihsph/ljhwZthlaukjlkulzlp/portal/bigtts/zh_female_popo_uranus_bigtts.mp3",
        "gender": "女",
        "flags": "🇨🇳🇺🇸"
    },
    {
        "voiceType": "zh_male_naiqimengwa_uranus_bigtts",
        "resourceId": "seed-tts-2.0",
        "name": "奶气萌娃 2.0",
        "nameEn": "Babyish Toddler 2.0",
        "description": "声线软萌稚嫩、奶气十足，软糯可爱的幼童音",
        "descriptionEn": "A soft, sweet and babyish toddler voice — adorable and cute.",
        "avatar": "https://lf3-static.bytednsdoc.com/obj/eden-cn/lm_hz_ihsph/ljhwZthlaukjlkulzlp/portal/bigtts/avatar/奶气萌娃.png",
        "trialUrl": "https://lf3-static.bytednsdoc.com/obj/eden-cn/lm_hz_ihsph/ljhwZthlaukjlkulzlp/portal/bigtts/zh_male_naiqimengwa_uranus_bigtts.mp3",
        "gender": "男",
        "flags": "🇨🇳🇺🇸"
    },
    {
        "voiceType": "zh_male_linjiananhai_uranus_bigtts",
        "resourceId": "seed-tts-2.0",
        "name": "邻家男孩 2.0",
        "nameEn": "Boy Next Door 2.0",
        "description": "声线干净清爽、语气亲切，阳光开朗的少年音",
        "descriptionEn": "A clean, refreshing, friendly and sunny boy voice.",
        "avatar": "https://lf3-static.bytednsdoc.com/obj/eden-cn/lm_hz_ihsph/ljhwZthlaukjlkulzlp/portal/bigtts/avatar/邻家男孩.png",
        "trialUrl": "https://lf3-static.bytednsdoc.com/obj/eden-cn/lm_hz_ihsph/ljhwZthlaukjlkulzlp/portal/bigtts/zh_male_linjiananhai_uranus_bigtts.mp3",
        "gender": "男",
        "flags": "🇨🇳🇺🇸"
    },
    {
        "voiceType": "zh_female_linjianvhai_uranus_bigtts",
        "resourceId": "seed-tts-2.0",
        "name": "邻家女孩 2.0",
        "nameEn": "Girl Next Door 2.0",
        "description": "软糯温柔的邻家女孩，低调内敛，耐心亲和",
        "descriptionEn": "A soft, gentle girl next door — understated, patient and warm.",
        "avatar": "https://lf3-static.bytednsdoc.com/obj/eden-cn/lm_hz_ihsph/ljhwZthlaukjlkulzlp/portal/bigtts/avatar/邻家女孩.png",
        "trialUrl": "https://lf3-static.bytednsdoc.com/obj/eden-cn/lm_hz_ihsph/ljhwZthlaukjlkulzlp/portal/bigtts/zh_female_linjianvhai_uranus_bigtts.mp3",
        "gender": "女",
        "flags": "🇨🇳🇺🇸"
    },
    {
        "voiceType": "zh_male_shaonianzixin_uranus_bigtts",
        "resourceId": "seed-tts-2.0",
        "name": "少年梓辛/Brayan 2.0",
        "nameEn": "Brayan 2.0",
        "description": "少年感十足的清爽男生，温柔亲切，阳光开朗",
        "descriptionEn": "A fresh, youthful boy voice — gentle, friendly and sunny.",
        "avatar": "https://lf3-static.bytednsdoc.com/obj/eden-cn/lm_hz_ihsph/ljhwZthlaukjlkulzlp/portal/bigtts/avatar/少年梓辛.png",
        "trialUrl": "https://lf3-static.bytednsdoc.com/obj/eden-cn/lm_hz_ihsph/ljhwZthlaukjlkulzlp/portal/bigtts/zh_male_shaonianzixin_uranus_bigtts.mp3",
        "gender": "男",
        "flags": "🇨🇳🇺🇸"
    },
    {
        "voiceType": "zh_male_liufei_uranus_bigtts",
        "resourceId": "seed-tts-2.0",
        "name": "刘飞 2.0",
        "nameEn": "Liu Fei 2.0",
        "description": "逻辑清晰、理性稳重的男性",
        "descriptionEn": "A clear-thinking, rational and steady male voice.",
        "avatar": "https://lf3-static.bytednsdoc.com/obj/eden-cn/lm_hz_ihsph/ljhwZthlaukjlkulzlp/portal/bigtts/avatar/刘飞.png",
        "trialUrl": "https://lf3-static.bytednsdoc.com/obj/eden-cn/lm_hz_ihsph/ljhwZthlaukjlkulzlp/portal/bigtts/zh_male_liufei_uranus_bigtts.mp3",
        "gender": "男",
        "flags": "🇨🇳🇺🇸"
    },
    {
        "voiceType": "zh_female_meilinvyou_uranus_bigtts",
        "resourceId": "seed-tts-2.0",
        "name": "魅力女友 2.0",
        "nameEn": "Charming Girlfriend 2.0",
        "description": "性感妩媚的御姐，成熟有魅力，风情十足",
        "descriptionEn": "A sexy, alluring mature woman — charming and full of allure.",
        "avatar": "https://lf3-static.bytednsdoc.com/obj/eden-cn/lm_hz_ihsph/ljhwZthlaukjlkulzlp/portal/bigtts/avatar/魅力女友.png",
        "trialUrl": "https://lf3-static.bytednsdoc.com/obj/eden-cn/lm_hz_ihsph/ljhwZthlaukjlkulzlp/portal/bigtts/zh_female_meilinvyou_uranus_bigtts.mp3",
        "gender": "女",
        "flags": "🇨🇳🇺🇸"
    },
    {
        "voiceType": "zh_female_shuangkuaisisi_uranus_bigtts",
        "resourceId": "seed-tts-2.0",
        "name": "爽快思思 2.0",
        "nameEn": "Easygoing Sisi 2.0",
        "description": "温暖直爽的邻家小妹，阳光热情，相处轻松自在",
        "descriptionEn": "A warm, straightforward girl next door — sunny, friendly and easy to be with.",
        "avatar": "https://lf3-static.bytednsdoc.com/obj/eden-cn/lm_hz_ihsph/ljhwZthlaukjlkulzlp/portal/bigtts/avatar/爽快思思.png",
        "trialUrl": "https://lf3-static.bytednsdoc.com/obj/eden-cn/lm_hz_ihsph/ljhwZthlaukjlkulzlp/portal/bigtts/zh_female_shuangkuaisisi_uranus_bigtts.mp3",
        "gender": "女",
        "flags": "🇨🇳🇺🇸"
    },
    {
        "voiceType": "zh_female_tianmeitaozi_uranus_bigtts",
        "resourceId": "seed-tts-2.0",
        "name": "甜美桃子 2.0",
        "nameEn": "Sweet Taozi 2.0",
        "description": "俏皮元气女生，开朗外向，自带活跃气氛的感染力",
        "descriptionEn": "A playful, energetic girl — cheerful, outgoing and infectious.",
        "avatar": "https://lf3-static.bytednsdoc.com/obj/eden-cn/lm_hz_ihsph/ljhwZthlaukjlkulzlp/portal/bigtts/avatar/甜美桃子.png",
        "trialUrl": "https://lf3-static.bytednsdoc.com/obj/eden-cn/lm_hz_ihsph/ljhwZthlaukjlkulzlp/portal/bigtts/zh_female_tianmeitaozi_uranus_bigtts.mp3",
        "gender": "女",
        "flags": "🇨🇳🇺🇸"
    },
    {
        "voiceType": "zh_female_qingxinnvsheng_uranus_bigtts",
        "resourceId": "seed-tts-2.0",
        "name": "清新女声 2.0",
        "nameEn": "Fresh Woman 2.0",
        "description": "气质出众的旗袍美人兼职场精英，明媚大方，魅力十足",
        "descriptionEn": "A standout qipao beauty and career elite — bright, gracious and charming.",
        "avatar": "https://lf3-static.bytednsdoc.com/obj/eden-cn/lm_hz_ihsph/ljhwZthlaukjlkulzlp/portal/bigtts/avatar/清新女声.png",
        "trialUrl": "https://lf3-static.bytednsdoc.com/obj/eden-cn/lm_hz_ihsph/ljhwZthlaukjlkulzlp/portal/bigtts/zh_female_qingxinnvsheng_uranus_bigtts.mp3",
        "gender": "女",
        "flags": "🇨🇳🇺🇸"
    },
    {
        "voiceType": "zh_male_taocheng_uranus_bigtts",
        "resourceId": "seed-tts-2.0",
        "name": "小天 2.0",
        "nameEn": "Xiaotian 2.0",
        "description": "眉目清朗男大，清澈温润有朝气，开朗真诚。",
        "descriptionEn": "A clear-faced college guy — pure, gentle, spirited, cheerful and sincere.",
        "avatar": "https://lf3-static.bytednsdoc.com/obj/eden-cn/lm_hz_ihsph/ljhwZthlaukjlkulzlp/portal/bigtts/avatar/小天.png",
        "trialUrl": "https://lf3-static.bytednsdoc.com/obj/eden-cn/lm_hz_ihsph/ljhwZthlaukjlkulzlp/portal/bigtts/zh_male_taocheng_uranus_bigtts.mp3",
        "gender": "男",
        "flags": "🇨🇳🇺🇸"
    },
    {
        "voiceType": "zh_male_m191_uranus_bigtts",
        "resourceId": "seed-tts-2.0",
        "name": "云舟 2.0",
        "nameEn": "Yunzhou 2.0",
        "description": "声音磁性的男生，成熟理性，做事有条理，让人信赖。",
        "descriptionEn": "A magnetic male voice — mature, rational, methodical and trustworthy.",
        "avatar": "https://lf3-static.bytednsdoc.com/obj/eden-cn/lm_hz_ihsph/ljhwZthlaukjlkulzlp/portal/bigtts/avatar/云舟.png",
        "trialUrl": "https://lf3-static.bytednsdoc.com/obj/eden-cn/lm_hz_ihsph/ljhwZthlaukjlkulzlp/portal/bigtts/zh_male_m191_uranus_bigtts.mp3",
        "gender": "男",
        "flags": "🇨🇳🇺🇸"
    },
    {
        "voiceType": "zh_female_tianmeixiaoyuan_uranus_bigtts",
        "resourceId": "seed-tts-2.0",
        "name": "甜美小源 2.0",
        "nameEn": "Sweet Xiaoyuan 2.0",
        "description": "声线明亮甜美的专业客服，亲切耐心，服务细致周到",
        "descriptionEn": "A bright, sweet professional customer-service voice — friendly, patient and attentive.",
        "avatar": "https://lf3-static.bytednsdoc.com/obj/eden-cn/lm_hz_ihsph/ljhwZthlaukjlkulzlp/portal/bigtts/avatar/甜美小源.png",
        "trialUrl": "https://lf3-static.bytednsdoc.com/obj/eden-cn/lm_hz_ihsph/ljhwZthlaukjlkulzlp/portal/bigtts/zh_female_tianmeixiaoyuan_uranus_bigtts.mp3",
        "gender": "女",
        "flags": "🇨🇳🇺🇸"
    },
    {
        "voiceType": "saturn_zh_female_wenrouwenya_tob",
        "resourceId": "seed-tts-2.0",
        "name": "温柔文雅 2.0",
        "nameEn": "Gentle & Refined 2.0",
        "description": "儒雅古风大小姐，温婉柔和，举手投足尽显典雅。",
        "descriptionEn": "A refined classical-style lady — gentle and graceful in every gesture.",
        "avatar": "https://lf3-static.bytednsdoc.com/obj/eden-cn/lm_hz_ihsph/ljhwZthlaukjlkulzlp/portal/bigtts/avatar/温柔文雅.png",
        "trialUrl": "https://lf3-static.bytednsdoc.com/obj/eden-cn/lm_hz_ihsph/ljhwZthlaukjlkulzlp/console/bigtts/ICL_zh_female_wenrouwenya_tob.mp3",
        "gender": "女",
        "flags": "🇨🇳🇺🇸"
    },
    {
        "voiceType": "zh_male_sophie_uranus_bigtts",
        "resourceId": "seed-tts-2.0",
        "name": "魅力苏菲",
        "nameEn": "Charming Sophie",
        "description": "高冷御姐，外表疏离难亲近，内心却细腻柔软",
        "descriptionEn": "An aloof, elegant lady — distant on the surface, tender within.",
        "avatar": "https://lf3-static.bytednsdoc.com/obj/eden-cn/lm_hz_ihsph/ljhwZthlaukjlkulzlp/portal/bigtts/avatar/魅力苏菲.png",
        "trialUrl": "https://lf3-static.bytednsdoc.com/obj/eden-cn/lm_hz_ihsph/ljhwZthlaukjlkulzlp/portal/bigtts/zh_male_sophie_uranus_bigtts.mp3",
        "gender": "女",
        "flags": "🇨🇳🇺🇸"
    }
];

/** Look up a voice by its voiceType. Returns undefined for null/unknown. */
export function findVoiceByType(voiceType: string | null | undefined): Voice | undefined {
    if (!voiceType) return undefined;
    return VOICES.find((v) => v.voiceType === voiceType);
}

// Localized accessors: Chinese UI shows the catalog (Chinese) text, everything else English.
// @/text is required lazily (not imported at module top) to avoid an import cycle:
// @/text → @/sync/persistence → … → @/sync/apiHappyVoice → Voices, which would
// otherwise leave React null and crash the voice settings screen.
function isChineseLocale(): boolean {
    const { getCurrentLanguage } = require('@/text') as typeof import('@/text');
    return getCurrentLanguage().startsWith('zh');
}

/** Localized display name for a voice. */
export function getVoiceName(voice: Voice): string {
    return isChineseLocale() ? voice.name : voice.nameEn;
}

/** Localized description for a voice. */
export function getVoiceDescription(voice: Voice): string {
    return isChineseLocale() ? voice.description : voice.descriptionEn;
}
